import { site, services } from './config.mjs';
import { button, ctaBand, differentiatorGrid, leadForm, offerCard, sectionIntro } from './components.mjs';

const processSteps = [
  ['01', 'Review the market', 'We discuss your service area, capacity, current demand and the work you want more of.'],
  ['02', 'Build the foundation', 'We build or restructure campaigns and check that calls and forms can be measured.'],
  ['03', 'Manage and learn', 'We review search terms, targeting, budgets and lead quality as the account runs.'],
  ['04', 'Report on business outcomes', 'We connect spend to estimates and booked moves when your systems make that possible.']
];

const stepGrid = (steps = processSteps) => `<div class="steps-grid">${steps.map(([n, title, copy]) => `<article class="step"><span class="step-number">${n}</span><h3>${title}</h3><p>${copy}</p></article>`).join('')}</div>`;

const pageHero = (eyebrow, title, copy, action = true) => `<section class="page-hero"><div class="container narrow"><p class="eyebrow">${eyebrow}</p><h1>${title}</h1><p class="hero-lead">${copy}</p>${action ? `<div class="hero-actions">${button()}</div>` : ''}</div></section>`;

const home = {
  path: '/',
  title: 'Google Ads for Independent Moving Companies | Field Proven Marketing',
  description: 'Operator-led Google Ads management for independent movers. Managed by Logan Arnold, a working moving company owner, with a focus on qualified calls, estimates and booked moves.',
  schema: true,
  content: `
    <section class="home-hero"><div class="container hero-grid"><div class="hero-copy"><p class="eyebrow">Field Proven Marketing</p><h1>Google Ads for <em>Independent Moving Companies</em></h1><p class="proof-line">Managed by a working moving company owner.</p><p class="hero-lead">Turn Google searches into qualified calls, estimates and booked moves. We manage paid search with a clear view of what happens after the lead reaches your office.</p><div class="hero-actions">${button()}${button(site.auditCta, '/contact/#market-review', true)}</div><p class="hero-footnote">Founded by Logan Arnold, a working moving company owner.</p></div><div class="journey-panel" aria-label="How paid search connects to booked work"><p class="panel-label">What we measure toward</p><h2>The lead is only the start.</h2><ol><li><span>01</span><strong>Relevant search</strong><small>Demand in your market</small></li><li><span>02</span><strong>Qualified call</strong><small>A real moving opportunity</small></li><li><span>03</span><strong>Estimate</strong><small>Fit, scope and timing</small></li><li><span>04</span><strong>Booked move</strong><small>Work your crews can deliver</small></li></ol><p>Each step informs what we change in the account.</p></div></div></section>
    <section class="section"><div class="container">${sectionIntro('Why Field Proven', 'A moving-company perspective changes the questions we ask.', 'Campaigns need to fit the operation behind them: service area, trucks, crews, call handling and profitable work.')}${differentiatorGrid()}</div></section>
    <section class="section section-soft"><div class="container split-layout"><div>${sectionIntro('Where spend loses value', 'More clicks do not always mean more good moves.')}<p>Searches outside your service area, calls that go unanswered, weak quote paths and reports that stop at form fills can all hide what paid search is really producing.</p><p>We review the whole path and make decisions based on the best evidence your business can provide.</p>${button('Explore Google Ads Services', '/google-ads-services', true)}</div><div class="issue-list"><div><span>01</span><p>Are the searches relevant to the moves you want?</p></div><div><span>02</span><p>Can prospects reach someone when they call?</p></div><div><span>03</span><p>Are inquiries turning into estimates?</p></div><div><span>04</span><p>Which estimates become booked work?</p></div></div></div></section>
    <section class="section"><div class="container">${sectionIntro('A practical process', 'From market review to clearer decisions.', 'No secret system. We show the work and keep the account in your hands.')}${stepGrid(processSteps.slice(0, 3))}<div class="section-link"><a class="text-link" href="/how-it-works">See the full process <span aria-hidden="true">↗</span></a></div></div></section>
    <section class="founder-band"><div class="container founder-grid"><div><p class="eyebrow eyebrow-light">Built by an operator</p><h2>Logan knows what a lead has to become.</h2></div><div><p>Logan Arnold founded Field Proven Marketing as a working moving company owner. He understands the gap between a marketing report and a calendar full of moves the crew can actually complete.</p><p>That operating context shapes how Field Proven targets demand, reviews calls and discusses results with owners.</p><a class="text-link light-link" href="/about">Meet Logan <span aria-hidden="true">↗</span></a></div></div></section>
    <section class="section"><div class="container offer-layout"><div>${sectionIntro('A clear starting point', 'The Founding Partner Program.')}<p>Built for independent movers with capacity, a sound reputation and the budget to test paid search properly.</p><p>The initial partnership gives us time to establish tracking, make changes and learn from the market. It is a working process, not a promise of a particular number of leads or bookings.</p>${button()}</div>${offerCard(true)}</div></section>
    ${ctaBand()}`
};

const ads = {
  path: '/google-ads-services',
  title: 'Google Ads Services for Moving Companies | Field Proven Marketing',
  description: 'Google Ads campaign management for independent movers, including search terms, conversion tracking, targeting, lead-quality review and booked-job reporting.',
  content: `${pageHero('Google Ads Services', 'Paid search built around the moving business.', 'Field Proven builds and manages Google Ads for independent movers, with attention to the searches, calls and booked work behind the account.')}
    <section class="section"><div class="container">${sectionIntro('What is included', 'The account work, from search to booked move.', 'The work is shaped by your market and the data available in your systems.')}<div class="service-grid">${services.map(([title, copy], i) => `<article class="service-item"><span class="item-index">${String(i + 1).padStart(2, '0')}</span><h3>${title}</h3><p>${copy}</p></article>`).join('')}</div></div></section>
    <section class="section section-soft"><div class="container split-layout"><div>${sectionIntro('Management with context', 'The account should fit the operation.')}<p>A campaign can generate inquiries and still miss the work you actually want. We discuss your service mix, the areas your trucks cover, seasonal demand and how calls become estimates.</p><p>Those details guide targeting and budget decisions. We review lead and call quality with you, then adjust based on what the evidence supports.</p></div><div class="plain-panel"><h3>What you stay in control of</h3><ul class="check-list"><li>Your Google Ads account and access</li><li>Payments to Google for ad spend</li><li>Visibility into campaign changes and data</li><li>Decisions about budget, service area and fit</li></ul></div></div></section>
    <section class="section"><div class="container offer-layout"><div>${sectionIntro('Current offer', 'Start with a focused 90-day partnership.')}<p>We use the first 90 days to establish a baseline, correct obvious gaps and learn which searches and inquiries are useful. Exact outcomes depend on the market, competition, budget, website, call handling and available capacity.</p>${button()}</div>${offerCard()}</div></section>${ctaBand('Talk through your market before you spend more.', 'We can discuss your current account, lead quality and the operating capacity behind your growth goals.')}`
};

const about = {
  path: '/about',
  title: 'About Logan Arnold & Field Proven Marketing',
  description: 'Meet Logan Arnold, founder of Field Proven Marketing and a working moving company owner.',
  content: `${pageHero('About Field Proven', 'Marketing led from inside the moving industry.', 'Field Proven Marketing was founded by Logan Arnold to give independent movers a paid-search partner who understands what happens after a customer calls.')}
    <section class="section"><div class="container about-grid"><div><p class="eyebrow">Meet the founder</p><h2>Logan Arnold</h2><p class="large-copy">Founder of Field Proven Marketing and a working moving company owner.</p></div><div class="prose"><p>Moving-company owners know that a lead is only useful when it fits the market, reaches the office, becomes an estimate and turns into work the crews can deliver. Logan built Field Proven around that complete path.</p><p>His operating perspective brings practical questions into Google Ads management: Which services have capacity? Where can the trucks profitably go? Are missed calls hiding demand? Are we tracking real opportunities or just counting form fills?</p><p>Field Proven starts with Google Ads and conversion tracking for independent movers. The goal is clear work, transparent reporting and decisions connected to booked business wherever the data allows.</p></div></div></section>
    <section class="section section-soft"><div class="container">${sectionIntro('How we work', 'Direct, transparent and accountable.')}<div class="value-grid"><article><h3>Focused</h3><p>Prioritize qualified demand and work that fits your operation.</p></article><article><h3>Reliable</h3><p>Document changes, address problems directly and follow through.</p></article><article><h3>Transparent</h3><p>Explain what changed, what the data supports and what remains uncertain.</p></article></div></div></section>
    <section class="section"><div class="container narrow statement"><p class="eyebrow">Our point of view</p><blockquote>“Marketing decisions should reflect actual business results, not vanity metrics.”</blockquote><p>We treat clicks and impressions as signals. Qualified calls, estimates and booked moves tell a fuller story.</p></div></section>${ctaBand('Have an owner-to-owner conversation.', 'Share your market and current challenges. We’ll start with what the evidence supports.')}`
};

const how = {
  path: '/how-it-works',
  title: 'How Our Google Ads Partnership Works | Field Proven Marketing',
  description: 'See how Field Proven reviews your moving market, builds campaigns, tracks inquiries, optimizes spend and reports on booked-job outcomes.',
  content: `${pageHero('How It Works', 'A clear process. An account you own.', 'We begin with your market and operating capacity, then work from search demand through inquiries, estimates and booked moves.')}
    <section class="section"><div class="container">${sectionIntro('The partnership', 'Five steps from review to reporting.')}<div class="timeline"><article><span>01</span><div><h3>15-minute market review</h3><p>We discuss your service area, current ads, the work you want more of and whether the partnership is a fit. We will not assume account problems we have not verified.</p></div></article><article><span>02</span><div><h3>Account and conversion review</h3><p>With access, we examine structure, search terms, targeting, calls and forms. We identify gaps and agree on priorities before major changes.</p></div></article><article><span>03</span><div><h3>Build or restructure</h3><p>We organize campaigns around services and locations, add relevant exclusions and put useful conversion tracking in place.</p></div></article><article><span>04</span><div><h3>Ongoing management</h3><p>We review demand, lead quality, call handling and capacity, then adjust bids, budgets, targeting and recommendations accordingly.</p></div></article><article><span>05</span><div><h3>Monthly business review</h3><p>We show spend, qualified inquiries and what can be connected to estimates and booked moves. We state where attribution is uncertain and agree on next actions.</p></div></article></div></div></section>
    <section class="section section-soft"><div class="container split-layout"><div>${sectionIntro('What we need from you', 'Useful context makes the work better.')}<p>Your service area, priority move types, operating capacity and access to the Google Ads account help us make informed decisions. Where possible, call, estimate and booking information lets us review quality beyond the initial inquiry.</p><p>You keep ownership of the account and pay Google directly for media spend.</p></div><div class="plain-panel"><h3>The first 90 days</h3><p>The Founding Partner Program begins with an initial 90-day partnership. That time allows for setup, early optimization and a more useful review of the market. Seasonality, competition, call handling and budget all affect what we learn.</p><p class="fine-print">Advertising performance varies. No specific result is guaranteed.</p></div></div></section>${ctaBand('Start with a short market review.', 'We’ll discuss fit, capacity and the questions your current data can answer.')}`
};

const contact = {
  path: '/contact',
  title: 'Request a Market Review | Field Proven Marketing',
  description: 'Request a 15-minute market review with Field Proven Marketing. Tell us about your moving company, market and current Google Ads activity.',
  content: `${pageHero('Contact', 'Let’s look at your market.', 'Tell us a little about your company and what you want to improve. Logan will review your note and follow up about a 15-minute market conversation.', false)}
    <section class="section contact-section"><div class="container contact-grid"><div><p class="eyebrow">Market review request</p><h2>A useful first conversation.</h2><p>We’ll discuss your market, the work your team can take on and whether Google Ads management is a fit. If you have an existing account, we can talk through what needs closer review.</p><div class="contact-direct"><h3>Prefer email?</h3><a href="mailto:${site.email}">${site.email}</a></div><p class="fine-print">Form submissions go to Field Proven Marketing by email. No commitment is required to request a review.</p></div><div class="form-panel">${leadForm()}</div></div></section>`
};

const privacy = {
  path: '/privacy-policy',
  title: 'Privacy Policy | Field Proven Marketing',
  description: 'How Field Proven Marketing handles information submitted through its website contact and market review forms.',
  content: `${pageHero('Privacy Policy', 'Your information, handled plainly.', 'Effective September 28, 2026. This policy explains the information this website collects and how it is used.', false)}
    <section class="section"><div class="container narrow prose policy"><h2>Information you provide</h2><p>When you submit a contact or market review form, we collect the details you enter, such as your name, company, email, phone, market, website, current Google Ads status, ad spend range and message. You can also choose to email us directly.</p><h2>How we use it</h2><p>We use this information to respond to your request, assess whether our services may be a fit and continue a conversation you initiate. We do not sell the information you submit through this website.</p><h2>Form delivery</h2><p>Our forms use FormSubmit to deliver submissions to ${site.email}. FormSubmit processes the submitted information to provide that delivery and spam filtering. Review <a href="https://formsubmit.co/privacy.pdf" target="_blank" rel="noopener noreferrer">FormSubmit’s privacy terms</a> for its practices. We keep received email correspondence as long as reasonably needed for the conversation or our business records.</p><h2>Website services</h2><p>This website loads Montserrat and Open Sans through Google Fonts. Your browser may send technical request information to Google to retrieve those fonts. We do not currently use an analytics service or advertising cookies on this website.</p><h2>Security and choices</h2><p>We take reasonable steps to limit access to inquiry information. No internet transmission is guaranteed to be completely secure. To ask about information you submitted or request deletion from our records, email <a href="mailto:${site.email}">${site.email}</a>. We may need to keep information where required for legitimate business or legal reasons.</p><h2>Updates</h2><p>If our website practices change, we will update this page and its effective date.</p><h2>Contact</h2><p>Field Proven Marketing<br /><a href="mailto:${site.email}">${site.email}</a></p></div></section>`
};

const faq = [
  ['Do you guarantee leads or booked moves?', 'No. Advertising performance varies, and no specific result is guaranteed. We explain what we can measure, what we change and what remains uncertain.'],
  ['Who owns the Google Ads account?', 'You do. Your company retains account access and pays Google directly for ad spend.'],
  ['What does the management fee cover?', 'Campaign builds or restructuring, search-term management, conversion tracking work, targeting, optimization, lead-quality review and monthly reporting.'],
  ['Is the Google ad budget included?', 'No. The Founding Partner Program is $1,000 setup and $1,000 per month for management. We recommend at least $2,500 per month in Google ad spend, paid directly to Google.'],
  ['What if we already run Google Ads?', 'We can review the existing account and discuss whether restructuring, tracking changes or a new management approach makes sense.'],
  ['How long is the initial partnership?', 'The Founding Partner Program starts with an initial 90-day partnership. We use that period to set the foundation and evaluate what the market data supports.']
];

const landing = {
  path: '/moving-company-google-ads',
  title: 'Moving Company Google Ads Management | Field Proven Marketing',
  description: 'Google Ads for independent moving companies, managed by Logan Arnold, a working moving company owner. Request a 15-minute market review.',
  minimal: true,
  schema: true,
  content: `
    <section class="landing-hero"><div class="container landing-hero-grid"><div><p class="eyebrow eyebrow-light">For independent movers</p><h1>Google Ads for moving companies, managed by a moving-company owner.</h1><p class="proof-line">Logan Arnold is a working moving company owner.</p><p>Field Proven helps connect search demand to qualified calls, estimates and booked moves, with the account and data in your hands.</p>${button(site.reviewCta, '#review-form')}<p class="hero-footnote">Advertising performance varies. No specific result is guaranteed.</p></div><div class="landing-proof"><span>OPERATOR PERSPECTIVE</span><strong>Trucks. Crews. Calls. Estimates. Booked work.</strong><p>Campaign decisions should account for the business that has to deliver the move.</p></div></div></section>
    <section class="section"><div class="container">${sectionIntro('The problem', 'Where moving-company Google Ads can go wrong.')}<div class="problem-grid"><article><h3>Traffic that cannot become a job</h3><p>Searches outside your area or for services your crews do not provide use budget without creating useful demand.</p></article><article><h3>Inquiries without context</h3><p>Clicks and form counts do not tell you whether calls were qualified, estimates were booked or jobs were profitable.</p></article><article><h3>Missed opportunities after the click</h3><p>A weak mobile page, missed call or slow follow-up can lose a real opportunity even when the ad did its job.</p></article></div></div></section>
    <section class="section section-soft"><div class="container">${sectionIntro('The difference', 'Built for how movers actually operate.')} ${differentiatorGrid()}</div></section>
    <section class="section"><div class="container split-layout"><div>${sectionIntro('Included', 'The work behind the campaign.')}<p>Field Proven manages the account and reviews the path from search to inquiry. Recommendations are grounded in the market, your operating capacity and the information your team can share.</p></div><div class="service-list"><ul class="check-list">${services.map(([title]) => `<li>${title}</li>`).join('')}</ul></div></div></section>
    <section class="section section-soft"><div class="container fit-grid"><div><p class="eyebrow">Good fit</p><h2>Built for independent operators ready to measure the work.</h2><ul class="check-list"><li>An established moving company with capacity for more profitable jobs</li><li>A clear service area and a website customers can use</li><li>A team willing to review call and lead quality</li><li>Budget for management plus meaningful ad testing</li></ul></div><div><p class="eyebrow">Probably not a fit</p><h2>We would rather be direct about fit.</h2><ul class="plain-list"><li>You need a guarantee of leads or booked moves</li><li>You cannot answer or follow up with incoming inquiries</li><li>You do not have capacity for additional work</li><li>You want an agency to own your account and hide the data</li></ul></div></div></section>
    <section class="section"><div class="container offer-layout"><div>${sectionIntro('Founding Partner Program', 'A clear investment and a focused start.')}<p>The management fee is separate from your Google ad spend. Your company pays Google directly and keeps account ownership.</p><p>We begin with an initial 90-day partnership to build the foundation, learn from the market and make informed adjustments.</p>${button(site.reviewCta, '#review-form')}</div>${offerCard()}</div></section>
    <section class="section section-soft"><div class="container">${sectionIntro('Simple process', 'Start with the market. Then do the work.')} ${stepGrid([['01', 'Request a review', 'Tell us about your market, capacity and current ads.'], ['02', 'Talk with Logan', 'Discuss fit and the questions your account and sales process need to answer.'], ['03', 'Build and manage', 'If we partner, we establish tracking, manage the campaigns and review business outcomes.']])}</div></section>
    <section class="section"><div class="container narrow">${sectionIntro('Frequently asked questions', 'What owners usually want to know.')}<div class="faq-list">${faq.map(([q, a]) => `<details><summary>${q}</summary><p>${a}</p></details>`).join('')}</div></div></section>
    <section class="section landing-form-section"><div class="container landing-form-grid"><div><p class="eyebrow">Request a review</p><h2>Tell Logan about your market.</h2><p>Share the basics. We’ll respond by email to discuss a 15-minute market review and whether Field Proven is a fit.</p><p class="fine-print">No commitment is required. Advertising performance varies; no specific result is guaranteed.</p></div><div class="form-panel">${leadForm({ short: true, id: 'review-form' })}</div></div></section>
    ${ctaBand('Find out what your market review should focus on.', 'A practical first conversation with a working moving company owner.')}`
};

export const pages = [home, ads, about, how, contact, privacy, landing];
